//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RANSA_PY_NET_CL.ServicioPedidoRansaNet {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoMovimientoRansa", Namespace="http://schemas.datacontract.org/2004/07/PY_RANSA_NET_WCF.Ws_RansaNet")]
    [System.SerializableAttribute()]
    public partial class PedidoMovimientoRansa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.ComponentModel.PropertyChangedEventHandler PropertyChanged1Field;
        
        private System.Nullable<System.DateTime> fecCreacionFieldField;
        
        private bool fecCreacionFieldSpecifiedField;
        
        private System.Nullable<System.DateTime> fecFinFieldField;
        
        private bool fecFinFieldSpecifiedField;
        
        private System.Nullable<System.DateTime> fecInicioFieldField;
        
        private bool fecInicioFieldSpecifiedField;
        
        private System.Nullable<System.DateTime> fecMovimeintoFieldField;
        
        private bool fecMovimeintoFieldSpecifiedField;
        
        private System.Nullable<System.DateTime> fecUpdateFieldField;
        
        private bool fecUpdateFieldSpecifiedField;
        
        private int idEstadopedidoFieldField;
        
        private bool idEstadopedidoFieldSpecifiedField;
        
        private int idPedidoFieldField;
        
        private bool idPedidoFieldSpecifiedField;
        
        private int idPedidoMovimientoFieldField;
        
        private bool idPedidoMovimientoFieldSpecifiedField;
        
        private int idUsuarioCreadorFieldField;
        
        private bool idUsuarioCreadorFieldSpecifiedField;
        
        private int idUsuarioUpdateFieldField;
        
        private bool idUsuarioUpdateFieldSpecifiedField;
        
        private string nomEstadoPedidoFieldField;
        
        private string nomUsuarioCreadorFieldField;
        
        private string nomUsuarioUpdateFieldField;
        
        private sbyte stsRegistroFieldField;
        
        private bool stsRegistroFieldSpecifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="PropertyChanged", IsRequired=true)]
        public System.ComponentModel.PropertyChangedEventHandler PropertyChanged1 {
            get {
                return this.PropertyChanged1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyChanged1Field, value) != true)) {
                    this.PropertyChanged1Field = value;
                    this.RaisePropertyChanged("PropertyChanged1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> fecCreacionField {
            get {
                return this.fecCreacionFieldField;
            }
            set {
                if ((this.fecCreacionFieldField.Equals(value) != true)) {
                    this.fecCreacionFieldField = value;
                    this.RaisePropertyChanged("fecCreacionField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool fecCreacionFieldSpecified {
            get {
                return this.fecCreacionFieldSpecifiedField;
            }
            set {
                if ((this.fecCreacionFieldSpecifiedField.Equals(value) != true)) {
                    this.fecCreacionFieldSpecifiedField = value;
                    this.RaisePropertyChanged("fecCreacionFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> fecFinField {
            get {
                return this.fecFinFieldField;
            }
            set {
                if ((this.fecFinFieldField.Equals(value) != true)) {
                    this.fecFinFieldField = value;
                    this.RaisePropertyChanged("fecFinField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool fecFinFieldSpecified {
            get {
                return this.fecFinFieldSpecifiedField;
            }
            set {
                if ((this.fecFinFieldSpecifiedField.Equals(value) != true)) {
                    this.fecFinFieldSpecifiedField = value;
                    this.RaisePropertyChanged("fecFinFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> fecInicioField {
            get {
                return this.fecInicioFieldField;
            }
            set {
                if ((this.fecInicioFieldField.Equals(value) != true)) {
                    this.fecInicioFieldField = value;
                    this.RaisePropertyChanged("fecInicioField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool fecInicioFieldSpecified {
            get {
                return this.fecInicioFieldSpecifiedField;
            }
            set {
                if ((this.fecInicioFieldSpecifiedField.Equals(value) != true)) {
                    this.fecInicioFieldSpecifiedField = value;
                    this.RaisePropertyChanged("fecInicioFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> fecMovimeintoField {
            get {
                return this.fecMovimeintoFieldField;
            }
            set {
                if ((this.fecMovimeintoFieldField.Equals(value) != true)) {
                    this.fecMovimeintoFieldField = value;
                    this.RaisePropertyChanged("fecMovimeintoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool fecMovimeintoFieldSpecified {
            get {
                return this.fecMovimeintoFieldSpecifiedField;
            }
            set {
                if ((this.fecMovimeintoFieldSpecifiedField.Equals(value) != true)) {
                    this.fecMovimeintoFieldSpecifiedField = value;
                    this.RaisePropertyChanged("fecMovimeintoFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> fecUpdateField {
            get {
                return this.fecUpdateFieldField;
            }
            set {
                if ((this.fecUpdateFieldField.Equals(value) != true)) {
                    this.fecUpdateFieldField = value;
                    this.RaisePropertyChanged("fecUpdateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool fecUpdateFieldSpecified {
            get {
                return this.fecUpdateFieldSpecifiedField;
            }
            set {
                if ((this.fecUpdateFieldSpecifiedField.Equals(value) != true)) {
                    this.fecUpdateFieldSpecifiedField = value;
                    this.RaisePropertyChanged("fecUpdateFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idEstadopedidoField {
            get {
                return this.idEstadopedidoFieldField;
            }
            set {
                if ((this.idEstadopedidoFieldField.Equals(value) != true)) {
                    this.idEstadopedidoFieldField = value;
                    this.RaisePropertyChanged("idEstadopedidoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool idEstadopedidoFieldSpecified {
            get {
                return this.idEstadopedidoFieldSpecifiedField;
            }
            set {
                if ((this.idEstadopedidoFieldSpecifiedField.Equals(value) != true)) {
                    this.idEstadopedidoFieldSpecifiedField = value;
                    this.RaisePropertyChanged("idEstadopedidoFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPedidoField {
            get {
                return this.idPedidoFieldField;
            }
            set {
                if ((this.idPedidoFieldField.Equals(value) != true)) {
                    this.idPedidoFieldField = value;
                    this.RaisePropertyChanged("idPedidoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool idPedidoFieldSpecified {
            get {
                return this.idPedidoFieldSpecifiedField;
            }
            set {
                if ((this.idPedidoFieldSpecifiedField.Equals(value) != true)) {
                    this.idPedidoFieldSpecifiedField = value;
                    this.RaisePropertyChanged("idPedidoFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPedidoMovimientoField {
            get {
                return this.idPedidoMovimientoFieldField;
            }
            set {
                if ((this.idPedidoMovimientoFieldField.Equals(value) != true)) {
                    this.idPedidoMovimientoFieldField = value;
                    this.RaisePropertyChanged("idPedidoMovimientoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool idPedidoMovimientoFieldSpecified {
            get {
                return this.idPedidoMovimientoFieldSpecifiedField;
            }
            set {
                if ((this.idPedidoMovimientoFieldSpecifiedField.Equals(value) != true)) {
                    this.idPedidoMovimientoFieldSpecifiedField = value;
                    this.RaisePropertyChanged("idPedidoMovimientoFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idUsuarioCreadorField {
            get {
                return this.idUsuarioCreadorFieldField;
            }
            set {
                if ((this.idUsuarioCreadorFieldField.Equals(value) != true)) {
                    this.idUsuarioCreadorFieldField = value;
                    this.RaisePropertyChanged("idUsuarioCreadorField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool idUsuarioCreadorFieldSpecified {
            get {
                return this.idUsuarioCreadorFieldSpecifiedField;
            }
            set {
                if ((this.idUsuarioCreadorFieldSpecifiedField.Equals(value) != true)) {
                    this.idUsuarioCreadorFieldSpecifiedField = value;
                    this.RaisePropertyChanged("idUsuarioCreadorFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idUsuarioUpdateField {
            get {
                return this.idUsuarioUpdateFieldField;
            }
            set {
                if ((this.idUsuarioUpdateFieldField.Equals(value) != true)) {
                    this.idUsuarioUpdateFieldField = value;
                    this.RaisePropertyChanged("idUsuarioUpdateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool idUsuarioUpdateFieldSpecified {
            get {
                return this.idUsuarioUpdateFieldSpecifiedField;
            }
            set {
                if ((this.idUsuarioUpdateFieldSpecifiedField.Equals(value) != true)) {
                    this.idUsuarioUpdateFieldSpecifiedField = value;
                    this.RaisePropertyChanged("idUsuarioUpdateFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomEstadoPedidoField {
            get {
                return this.nomEstadoPedidoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nomEstadoPedidoFieldField, value) != true)) {
                    this.nomEstadoPedidoFieldField = value;
                    this.RaisePropertyChanged("nomEstadoPedidoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomUsuarioCreadorField {
            get {
                return this.nomUsuarioCreadorFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nomUsuarioCreadorFieldField, value) != true)) {
                    this.nomUsuarioCreadorFieldField = value;
                    this.RaisePropertyChanged("nomUsuarioCreadorField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomUsuarioUpdateField {
            get {
                return this.nomUsuarioUpdateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nomUsuarioUpdateFieldField, value) != true)) {
                    this.nomUsuarioUpdateFieldField = value;
                    this.RaisePropertyChanged("nomUsuarioUpdateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public sbyte stsRegistroField {
            get {
                return this.stsRegistroFieldField;
            }
            set {
                if ((this.stsRegistroFieldField.Equals(value) != true)) {
                    this.stsRegistroFieldField = value;
                    this.RaisePropertyChanged("stsRegistroField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool stsRegistroFieldSpecified {
            get {
                return this.stsRegistroFieldSpecifiedField;
            }
            set {
                if ((this.stsRegistroFieldSpecifiedField.Equals(value) != true)) {
                    this.stsRegistroFieldSpecifiedField = value;
                    this.RaisePropertyChanged("stsRegistroFieldSpecified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPedidoRansaNet.ServicioPedido")]
    public interface ServicioPedido {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioPedido/RegistrarPedidoMovimiento", ReplyAction="http://tempuri.org/ServicioPedido/RegistrarPedidoMovimientoResponse")]
        bool RegistrarPedidoMovimiento(PY_RANSA_NET_EN.Cls_PedidoEN pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioPedido/ConsultaPedidoMovimiento", ReplyAction="http://tempuri.org/ServicioPedido/ConsultaPedidoMovimientoResponse")]
        System.Collections.Generic.List<RANSA_PY_NET_CL.ServicioPedidoRansaNet.PedidoMovimientoRansa> ConsultaPedidoMovimiento(string pStr_CodPedido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioPedidoChannel : RANSA_PY_NET_CL.ServicioPedidoRansaNet.ServicioPedido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPedidoClient : System.ServiceModel.ClientBase<RANSA_PY_NET_CL.ServicioPedidoRansaNet.ServicioPedido>, RANSA_PY_NET_CL.ServicioPedidoRansaNet.ServicioPedido {
        
        public ServicioPedidoClient() {
        }
        
        public ServicioPedidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPedidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPedidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPedidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarPedidoMovimiento(PY_RANSA_NET_EN.Cls_PedidoEN pedido) {
            return base.Channel.RegistrarPedidoMovimiento(pedido);
        }
        
        public System.Collections.Generic.List<RANSA_PY_NET_CL.ServicioPedidoRansaNet.PedidoMovimientoRansa> ConsultaPedidoMovimiento(string pStr_CodPedido) {
            return base.Channel.ConsultaPedidoMovimiento(pStr_CodPedido);
        }
    }
}
