'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:logeowsdl", ConfigurationName:="ServiceReference1.logeowsdlPortType")>  _
    Public Interface logeowsdlPortType
        
        'CODEGEN: Generating message contract since the wrapper namespace (urn:hellowsdl) of message helloRequest does not match the default value (urn:logeowsdl)
        <System.ServiceModel.OperationContractAttribute(Action:="urn:hellowsdl#hello", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function hello(ByVal request As ServiceReference1.helloRequest) As ServiceReference1.helloResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:logeowsdl#logeo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function logeo(ByVal usuario As String, ByVal clave As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Boolean
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="hello", WrapperNamespace:="urn:hellowsdl", IsWrapped:=true)>  _
    Partial Public Class helloRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public name As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String)
            MyBase.New
            Me.name = name
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="helloResponse", WrapperNamespace:="urn:hellowsdl", IsWrapped:=true)>  _
    Partial Public Class helloResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface logeowsdlPortTypeChannel
        Inherits ServiceReference1.logeowsdlPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class logeowsdlPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.logeowsdlPortType)
        Implements ServiceReference1.logeowsdlPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_logeowsdlPortType_hello(ByVal request As ServiceReference1.helloRequest) As ServiceReference1.helloResponse Implements ServiceReference1.logeowsdlPortType.hello
            Return MyBase.Channel.hello(request)
        End Function
        
        Public Function hello(ByVal name As String) As String
            Dim inValue As ServiceReference1.helloRequest = New ServiceReference1.helloRequest()
            inValue.name = name
            Dim retVal As ServiceReference1.helloResponse = CType(Me,ServiceReference1.logeowsdlPortType).hello(inValue)
            Return retVal.[return]
        End Function
        
        Public Function logeo(ByVal usuario As String, ByVal clave As String) As Boolean Implements ServiceReference1.logeowsdlPortType.logeo
            Return MyBase.Channel.logeo(usuario, clave)
        End Function
    End Class
End Namespace
